### ISSUE TITLE
Bail (with warning) when we fail to parse versions

### ISSUE THREAD

**Issue by djspiewak** [dwijnand/sbt-travisci#8]
Much to my surprise, we actually need this feature!  My proposal would be to default the implementation of `crossScalaVersions` to `crossScalaVersions.value` (i.e. inherited value) when we either a) can't find `.travis.yml`, or b) can't parse a set of versions.  We should have a distinct warning for each case.

**Comment by dwijnand** [comment]
Help me understand, why can't we blow up?

**Comment by djspiewak** [comment]
We have found that it's not unusual for someone to set up a project for local experimentation and bring in our plugin infrastructure (which includes sbt-travisci) without setting up a .travis.yml.  We could just require explicit triggering of the Travis support, but I would prefer to warn and drop to defaulted values to avoid extra boilerplate in the common case.

**Comment by dwijnand** [comment]
I see. Fair enough.

Hopefully the defaulting works (IIRC crossScalaVersions uses derive, which is... "Interesting")

Are you doing this or do you want me to (not right now)?

**Comment by djspiewak** [comment]
I'll do it. Just wanted to get your buy-in first. :-)
